// The client build: every client/**/*.ts is emitted as the SAME path under
// public/js/**/*.js — one file in, one file out, no bundling, so the pages'
// native ES-module graph, the ids the tests look for and the Replit Run button
// are untouched. Type checking is `npm run typecheck` (tsc --noEmit); this
// script only strips the types (esbuild). The emitted .js is NOT committed
// (public/js/ is gitignored): `npm start`'s prestart and `npm test`'s pretest
// emit it, so esbuild is a runtime dependency and a checkout runs the build
// before the server imports public/js/shared/*. Edit the .ts, never the .js.
// test/build.test.mjs proves the emit is current and every emitted file has
// a source.
import { readdirSync, statSync } from "node:fs"
import { join, relative } from "node:path"
import { fileURLToPath } from "node:url"

const root = fileURLToPath(new URL("..", import.meta.url))
const SRC = join(root, "client")
const OUT = join(root, "public", "js")

export function sourceFiles(dir = SRC) {
  const out = []
  for (const name of readdirSync(dir)) {
    const p = join(dir, name)
    if (statSync(p).isDirectory()) out.push(...sourceFiles(p))
    else if (name.endsWith(".ts") && !name.endsWith(".d.ts")) out.push(p)
  }
  return out.sort()
}

export const emittedPath = (src) => join(OUT, relative(SRC, src)).replace(/\.ts$/, ".js")

export const BANNER = "// GENERATED by scripts/build.mjs from client/ — edit the .ts source, not this file."

// The esbuild options, shared with test/build.test.mjs so a fresh emit there
// is byte-identical. charset utf8: emoji stay emoji in the emitted source
// (the page tests regex them; the default would escape them to \u{…}).
export const esbuildOptions = ({ minify = false, outdir = OUT } = {}) => ({
  outdir,
  outbase: SRC,
  format: "esm",
  target: "es2022",
  bundle: false,
  minify,
  charset: "utf8",
  banner: { js: BANNER },
  logLevel: "warning",
})

// esbuild is loaded lazily so importing this module (the test does, for the
// options) never needs it; a missing install is reported plainly.
async function loadEsbuild() {
  try {
    return (await import("esbuild")).build
  } catch (e) {
    if (e?.code === "ERR_MODULE_NOT_FOUND") return null
    throw e
  }
}

// Returns the entry points it emitted, or null when esbuild isn't installed.
export async function buildClient({ minify = false } = {}) {
  const build = await loadEsbuild()
  if (!build) return null
  const entryPoints = sourceFiles()
  if (!entryPoints.length) return []
  await build({ entryPoints, ...esbuildOptions({ minify }) })
  return entryPoints
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const files = await buildClient({ minify: process.argv.includes("--minify") })
  if (files === null) {
    console.error("esbuild is not installed — public/js cannot be emitted (run npm install; esbuild is a dependency)")
    process.exit(1)
  }
  else console.log(`built ${files.length} client module(s) → public/js`)
}
